export const PATH_INICIAL = '/'
export const PATH_NOT_FOUND = '*'
export const PATH_LOGIN = '/login'
export const PATH_MAIN = '/home'
export const PATH_ACCESS_DENIED = '/access-denied'
export const PATH_CONSULTATIONS = '/my-consultations'
export const PATH_THERAPIST_DASHBOARD = '/therapist-dashboard'